package org.paron.syncservice.model;


import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

/*
 * JPA Entity — maps to the "offline_transactions" table.
 *
 * One row here = one payment the user made while offline (e.g. paid a
 * merchant ₹150 using their phone with no internet). The device collects
 * several of these locally, then sends them all at once when it reconnects.
 *
 * deviceTransactionId is the KEY field for idempotency — explained in
 * IdempotencyService. It is generated by the MOBILE DEVICE itself at the
 * moment of payment (e.g. a UUID created on-device), not by our backend.
 * This means even if the same transaction is sent to us twice (duplicate
 * network retry), it always carries the same ID, so we can recognize and
 * skip the duplicate.
 */
@Entity
@Table(name="offline_transactions",indexes={
        @Index(name="idx_txn_device_id",columnList="device_transaction_id",unique=true),
        @Index(name = "idx_txn_status",    columnList = "status"),
        @Index(name = "idx_txn_user_id",   columnList = "user_id")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class OfflineTransaction {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    // Generated by the device at payment time — our idempotency anchor.
    // Unique constraint at the DB level is a second line of defense
    @Column(name = "device_transaction_id", nullable = false, unique = true)
    private String deviceTransactionId;

    @Column(name = "user_id", nullable = false)
    private String userId;

    // The full offline spending JWT this transaction was made against
    @Column(name = "offline_token", nullable = false, columnDefinition = "TEXT")
    private String offlineToken;

    @Column(name = "amount", nullable = false, precision = 12, scale = 2)
    private BigDecimal amount;

    @Column(name = "merchant_id")
    private String merchantId;

    // The phone's stable device identifier — feeds the fraud-service
    // TOKEN_REUSE rule so the same token spent from a second device is
    // flagged instead of silently passing.
    @Column(name = "device_id")
    private String deviceId;

    // Signed-receipt evidence (Step 0b): the device's ECDSA signature over
    // the canonical transaction, plus the JWK public key it verifies with.
    // Persisted so fraud review and the dispute arbiter can re-check
    // authenticity later instead of trusting the stored row blindly.
    @Column(name = "signature", columnDefinition = "TEXT")
    private String signature;

    @Column(name = "public_key", columnDefinition = "TEXT")
    private String publicKey;

    // When the payment actually happened offline (set by the device clock,
    // NOT when it reached our server — important for fraud time-pattern checks)
    @Column(name = "transacted_at", nullable = false)
    private LocalDateTime transactedAt;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    @Builder.Default
    private TransactionStatus status = TransactionStatus.RECEIVED;

    // Populated once the fraud-service responds (kept simple here — real
    // fraud-service call happens in SettlementProcessor)
    @Column(name = "fraud_score")
    private Double fraudScore;

    @Column(name = "rejection_reason")
    private String rejectionReason;

    @Column(name = "received_at", nullable = false, updatable = false)
    @Builder.Default
    private LocalDateTime receivedAt = LocalDateTime.now();

    @Column(name = "settled_at")
    private LocalDateTime settledAt;
}
